### ISSUE TITLE
exometer (aflinux) doesn't build on OS X 10.7.5

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#797]
Exometer uses aflinux for connecting to statsd and riak.
This is optional for dev environments and even for production.

On OS X 10.7.5 I get compile errors.
aflinux won't compile on anything non-unix as well (think Windows).

Can we make aflinux an optional include for exometer?
And if so, how can we get that dependency in the rebar.config?

Error log on OS X 10.7.5

```
==> afunix (compile)
Compiling /Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:3080:57: error: use of undeclared identifier 'SO_PEERCRED'
            if (IS_SOCKET_ERROR(sock_getopt(desc->s,SOL_SOCKET,SO_PEERCRED,
                                                               ^
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:148:57: note: expanded from macro 'sock_getopt'
#define sock_getopt(s,t,n,v,l)      getsockopt((s),(t),(n),(v),(l))
                                                        ^
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:58:32: note: expanded from macro 'IS_SOCKET_ERROR'
#define IS_SOCKET_ERROR(val) ((val) < 0)
                               ^
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:3086:18: error: no member named 'pid' in 'struct ucred'
            put_int32(u.pid, ptr);
            ~~~~~~~~~~~~^~~~~~~~~
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:245:55: note: expanded from macro 'put_int32'
#define put_int32(i, s) do {((char*)(s))[0] = (char)((i) >> 24) & 0xff;   \
                                                      ^
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:3086:18: error: no member named 'pid' in 'struct ucred'
            put_int32(u.pid, ptr);
            ~~~~~~~~~~~~^~~~~~~~~
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:246:55: note: expanded from macro 'put_int32'
                            ((char*)(s))[1] = (char)((i) >> 16) & 0xff;   \
                                                      ^
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:3086:18: error: no member named 'pid' in 'struct ucred'
            put_int32(u.pid, ptr);
            ~~~~~~~~~~~~^~~~~~~~~
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:247:55: note: expanded from macro 'put_int32'
                            ((char*)(s))[2] = (char)((i) >> 8)  & 0xff;   \
                                                      ^
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:3086:18: error: no member named 'pid' in 'struct ucred'
            put_int32(u.pid, ptr);
            ~~~~~~~~~~~~^~~~~~~~~
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:248:54: note: expanded from macro 'put_int32'
                            ((char*)(s))[3] = (char)(i)         & 0xff;} \
                                                     ^
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:3871:45: warning: incompatible integer to pointer conversion passing 'long' to parameter of type 'ErlDrvPort' (aka 'struct _erl_drv_port *'); 
    port =  (ErlDrvPort) driver_create_port(CREATE_CAST port, owner, "tcp_inet", (ErlDrvData) ((long)copy_desc));
                                            ^~~~~~~~~~~~~~~~
/Users/marc/Sites/zotonic-mx/deps/afunix/c_src/afunix_drv.c:3826:21: note: expanded from macro 'CREATE_CAST'
#define CREATE_CAST (long)
                    ^~~~~~
/usr/local/lib/erlang/erts-5.9.3.1/include/erl_driver.h:598:49: note: passing argument to parameter 'creator_port' here
EXTERN ErlDrvPort driver_create_port(ErlDrvPort creator_port, 
                                                ^
1 warning and 5 errors generated.
ERROR: compile failed while processing /Users/marc/Sites/zotonic-mx/deps/afunix: rebar_abort
```

cc @mmzeeman @arjan @kaos
